DROP TABLE IF EXISTS collection_record;
DROP TABLE IF EXISTS collection_task;

CREATE TABLE collection_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_account_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    contract_number VARCHAR(50) NOT NULL,
    overdue_days INT NOT NULL,
    overdue_principal DECIMAL(15,2) NOT NULL,
    overdue_interest DECIMAL(15,2) NOT NULL,
    overdue_total DECIMAL(15,2) NOT NULL,
    penalty_rate DECIMAL(10,6) DEFAULT 0.0005,
    last_calculated_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    assigned_to BIGINT,
    priority VARCHAR(20) DEFAULT 'MEDIUM',
    last_contact_date DATE,
    next_contact_date DATE,
    promise_amount DECIMAL(15,2),
    promise_date DATE,
    notes CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_collection_task_loan_account ON collection_task (loan_account_id);
CREATE INDEX idx_collection_task_customer ON collection_task (customer_id);
CREATE INDEX idx_collection_task_status ON collection_task (status);
CREATE INDEX idx_collection_task_assigned_to ON collection_task (assigned_to);
CREATE INDEX idx_collection_task_priority ON collection_task (priority);
CREATE INDEX idx_collection_task_overdue_days ON collection_task (overdue_days);
CREATE INDEX idx_collection_task_next_contact ON collection_task (next_contact_date);
CREATE INDEX idx_collection_task_last_calculated ON collection_task (last_calculated_at);

CREATE TABLE collection_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_task_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    contact_method VARCHAR(20) NOT NULL,
    contact_result VARCHAR(20) NOT NULL,
    contact_time TIMESTAMP NOT NULL,
    notes CLOB,
    next_action VARCHAR(255),
    next_contact_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_collection_record_task ON collection_record (collection_task_id);
CREATE INDEX idx_collection_record_operator ON collection_record (operator_id);
CREATE INDEX idx_collection_record_contact_time ON collection_record (contact_time);
